"""empty message

Revision ID: 215b371c2aac
Revises: d36c610472e7
Create Date: 2022-04-16 19:50:09.349307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215b371c2aac'
down_revision = 'd36c610472e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
