"""empty message

Revision ID: 7cc33fb290c1
Revises: cf9273b97e84
Create Date: 2022-05-15 16:01:57.659717

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7cc33fb290c1'
down_revision = 'cf9273b97e84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('time_expire', sa.Time(), nullable=True))
    op.drop_column('task', 'datetime_expire')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('datetime_expire', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('task', 'time_expire')
    # ### end Alembic commands ###
