"""empty message

Revision ID: aa9aab9fb65e
Revises: 215b371c2aac
Create Date: 2022-04-17 13:47:26.651965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa9aab9fb65e'
down_revision = '215b371c2aac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('public_id', sa.String(length=50), nullable=True))
    op.create_unique_constraint(op.f('uq_user_public_id'), 'user', ['public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_public_id'), 'user', type_='unique')
    op.drop_column('user', 'public_id')
    # ### end Alembic commands ###
