"""empty message

Revision ID: cf9273b97e84
Revises: 215b371c2aac
Create Date: 2022-04-21 01:05:00.830880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cf9273b97e84'
down_revision = '215b371c2aac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('public_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_unique_constraint(op.f('uq_user_public_id'), 'user', ['public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_public_id'), 'user', type_='unique')
    op.drop_column('user', 'public_id')
    # ### end Alembic commands ###
