"""empty message

Revision ID: d36c610472e7
Revises:
Create Date: 2022-04-13 23:14:01.610062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd36c610472e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email'))
    )
    op.create_index(op.f('ix_user_uid'), 'user', ['uid'], unique=False)
    op.create_table('task',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('date_expire', sa.Date(), nullable=True),
    sa.Column('datetime_expire', sa.DateTime(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('user_uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_uid'], ['user.uid'], name=op.f('fk_task_user_uid_user')),
    sa.PrimaryKeyConstraint('uid', name=op.f('pk_task'))
    )
    op.create_index(op.f('ix_task_uid'), 'task', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_uid'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_user_uid'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
